# coding: utf-8

"""
    Instrument Quote Source API (administrator)

    An ASP.NET Core Web API service for getting information about instrument quotes. Administrator tools to extend avaliable data  # noqa: E501

    OpenAPI spec version: v2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TimeFrameResponseDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'code': 'str',
        'seconds': 'int'
    }

    attribute_map = {
        'id': 'id',
        'code': 'code',
        'seconds': 'seconds'
    }

    def __init__(self, id=None, code=None, seconds=None):  # noqa: E501
        """TimeFrameResponseDto - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._code = None
        self._seconds = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if code is not None:
            self.code = code
        if seconds is not None:
            self.seconds = seconds

    @property
    def id(self):
        """Gets the id of this TimeFrameResponseDto.  # noqa: E501


        :return: The id of this TimeFrameResponseDto.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TimeFrameResponseDto.


        :param id: The id of this TimeFrameResponseDto.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def code(self):
        """Gets the code of this TimeFrameResponseDto.  # noqa: E501


        :return: The code of this TimeFrameResponseDto.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this TimeFrameResponseDto.


        :param code: The code of this TimeFrameResponseDto.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def seconds(self):
        """Gets the seconds of this TimeFrameResponseDto.  # noqa: E501


        :return: The seconds of this TimeFrameResponseDto.  # noqa: E501
        :rtype: int
        """
        return self._seconds

    @seconds.setter
    def seconds(self, seconds):
        """Sets the seconds of this TimeFrameResponseDto.


        :param seconds: The seconds of this TimeFrameResponseDto.  # noqa: E501
        :type: int
        """

        self._seconds = seconds

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TimeFrameResponseDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TimeFrameResponseDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
