# coding: utf-8

"""
    Instrument Quote Source API (administrator)

    An ASP.NET Core Web API service for getting information about instrument quotes. Administrator tools to extend avaliable data  # noqa: E501

    OpenAPI spec version: v2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UploadedCandlesDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'from_date': 'date',
        'untill_date': 'date',
        'candles': 'list[CandleDto]'
    }

    attribute_map = {
        'from_date': 'fromDate',
        'untill_date': 'untillDate',
        'candles': 'candles'
    }

    def __init__(self, from_date=None, untill_date=None, candles=None):  # noqa: E501
        """UploadedCandlesDto - a model defined in Swagger"""  # noqa: E501
        self._from_date = None
        self._untill_date = None
        self._candles = None
        self.discriminator = None
        self.from_date = from_date
        self.untill_date = untill_date
        if candles is not None:
            self.candles = candles

    @property
    def from_date(self):
        """Gets the from_date of this UploadedCandlesDto.  # noqa: E501


        :return: The from_date of this UploadedCandlesDto.  # noqa: E501
        :rtype: date
        """
        return self._from_date

    @from_date.setter
    def from_date(self, from_date):
        """Sets the from_date of this UploadedCandlesDto.


        :param from_date: The from_date of this UploadedCandlesDto.  # noqa: E501
        :type: date
        """
        if from_date is None:
            raise ValueError("Invalid value for `from_date`, must not be `None`")  # noqa: E501

        self._from_date = from_date

    @property
    def untill_date(self):
        """Gets the untill_date of this UploadedCandlesDto.  # noqa: E501


        :return: The untill_date of this UploadedCandlesDto.  # noqa: E501
        :rtype: date
        """
        return self._untill_date

    @untill_date.setter
    def untill_date(self, untill_date):
        """Sets the untill_date of this UploadedCandlesDto.


        :param untill_date: The untill_date of this UploadedCandlesDto.  # noqa: E501
        :type: date
        """
        if untill_date is None:
            raise ValueError("Invalid value for `untill_date`, must not be `None`")  # noqa: E501

        self._untill_date = untill_date

    @property
    def candles(self):
        """Gets the candles of this UploadedCandlesDto.  # noqa: E501


        :return: The candles of this UploadedCandlesDto.  # noqa: E501
        :rtype: list[CandleDto]
        """
        return self._candles

    @candles.setter
    def candles(self, candles):
        """Sets the candles of this UploadedCandlesDto.


        :param candles: The candles of this UploadedCandlesDto.  # noqa: E501
        :type: list[CandleDto]
        """

        self._candles = candles

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UploadedCandlesDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UploadedCandlesDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
