# coding: utf-8

"""
    Instrument Quote Source API

    An ASP.NET Core Web API service for getting information about instrument quotes  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NewCandlesDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_from': 'datetime',
        'untill': 'datetime',
        'candles': 'list[CandleDto]'
    }

    attribute_map = {
        '_from': 'from',
        'untill': 'untill',
        'candles': 'candles'
    }

    def __init__(self, _from=None, untill=None, candles=None):  # noqa: E501
        """NewCandlesDto - a model defined in Swagger"""  # noqa: E501
        self.__from = None
        self._untill = None
        self._candles = None
        self.discriminator = None
        if _from is not None:
            self._from = _from
        if untill is not None:
            self.untill = untill
        if candles is not None:
            self.candles = candles

    @property
    def _from(self):
        """Gets the _from of this NewCandlesDto.  # noqa: E501


        :return: The _from of this NewCandlesDto.  # noqa: E501
        :rtype: datetime
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this NewCandlesDto.


        :param _from: The _from of this NewCandlesDto.  # noqa: E501
        :type: datetime
        """

        self.__from = _from

    @property
    def untill(self):
        """Gets the untill of this NewCandlesDto.  # noqa: E501


        :return: The untill of this NewCandlesDto.  # noqa: E501
        :rtype: datetime
        """
        return self._untill

    @untill.setter
    def untill(self, untill):
        """Sets the untill of this NewCandlesDto.


        :param untill: The untill of this NewCandlesDto.  # noqa: E501
        :type: datetime
        """

        self._untill = untill

    @property
    def candles(self):
        """Gets the candles of this NewCandlesDto.  # noqa: E501


        :return: The candles of this NewCandlesDto.  # noqa: E501
        :rtype: list[CandleDto]
        """
        return self._candles

    @candles.setter
    def candles(self, candles):
        """Sets the candles of this NewCandlesDto.


        :param candles: The candles of this NewCandlesDto.  # noqa: E501
        :type: list[CandleDto]
        """

        self._candles = candles

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NewCandlesDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NewCandlesDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
